twitter_stream:
  outputs:
    dev:
      dataset: stream_stg
      fixed_retries: 1
      keyfile: ~/.google/credentials/google_credentials.json
      location: europe-west9
      method: service-account
      priority: interactive
      project: '{{ env_var(''GCP_PROJECT_ID'') }}'
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: stream_prod
      fixed_retries: 1
      keyfile: ~/.google/credentials/google_credentials.json
      location: europe-west9
      method: service-account
      priority: interactive
      project: '{{ env_var(''GCP_PROJECT_ID'') }}'
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
