version: 2

models:
  - name: dim_user
    description: >
      User information.

  - name: dim_language
    description: >
      language code conversion.
      
  - name: fact_tweets
    description: >
      All the tweets available.

  - name: dim_trendings
    description: >
      Trending hashtags by hour.

  - name: dim_language_hour
    description: >
      Trendingg languages by hour.

sources:
  - name: seed
    schema: public
    tables:
      - name: lang_names
        seed:
          enabled: true
          # Specify the path to the seed file
          files:
            - path: seeds/lang_names.csv