version: 2

models:
  - name: dim_user
    description: >
      User information.

  - name: dim_tweet
    description: >
      Information about the tweet.
      
  - name: fact_tweets
    description: >
      All the tweets available.

  - name: trending_hashtags_hourly
    description: >
      Trending hashtags by hour.

  - name: language_usage_hourly
    description: >
      Trending languages by hour.
  
  - name: wide_stream
    description: >
      Grouped data from reporting purpose.
  
  - name: dim_time
    description: >
      Time of the tweet.

sources:
  - name: seed
    schema: public
    tables:
      - name: lang_names
        seed:
          enabled: true
          # Specify the path to the seed file
          files:
            - path: seeds/lang_names.csv


sources:
    - name: staging
      database: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: stream_stg
      tables:
        - name: stg_raw_tweets
        - name: lang_names